title: Michael Herold
email: michael@michaeljherold.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: ""
url: "https://michaeljherold.com"

source: "src"
destination: "dist"
exclude:
  - "assets"

future: true
show_drafts: true
limit_posts: 10

social:
  github:
    url: "https://github.com/michaelherold"
    username: "michaelherold"
  twitter:
    url: "https://twitter.com/mherold"
    username: "@mherold"

markdown: "redcarpet"
redcarpet:
  extensions:
    - "autolink"
    - "fenced_code_blocks"
    - "footnotes"
    - "highlight"
    - "no_intra_emphasis"
    - "smart"
    - "strikethrough"
    - "superscript"
    - "tables"
    - "underline"

gems:
  - "jekyll-archives"
  - "jekyll-feed"
  - "jekyll-paginate"
  - "jekyll-sitemap"
  - "jekyll-seo-tag"

jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layouts:
    year: "year-archive"
    month: "month-archive"
    category: "category-archive"
    tag: "tag-archive"
  permalinks:
    year: "/archive/:year/"
    month: "/archive/:year/:month/"
    category: "/category/:name/"
    tags: "/tag/:name/"
