title: Michael Herold
email: michael@michaeljherold.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: ""
url: "https://michaeljherold.com"
logo: ""

source: "src"
destination: "dist"
exclude:
  - "assets"

future: true
show_drafts: true
limit_posts: 10

author:
  bio: "This is my bio"
  email: "michael@michaeljherold.com"
  github: "michaelherold"
  name: "Michael Herold"
  twitter: "mherold"
  uri: "https://michaeljherold.com"

github: &github
  url: "https://github.com/michaelherold"
  username: "michaelherold"

twitter: &twitter
  url: "https://twitter.com/mherold"
  username: "mherold"

social:
  name: "Michael Herold"
  links:
    - "https://github.com/michaelherold"
    - "https://plus.google.com/u/0/103923072862453006975"
    - "https://twitter.com/mherold"
    - "https://www.facebook.com/michael.j.herold"
    - "https://www.linkedin.com/in/michaeljherold"

social_links:
  github: *github
  twitter: *twitter

markdown: "redcarpet"
redcarpet:
  extensions:
    - "autolink"
    - "fenced_code_blocks"
    - "footnotes"
    - "highlight"
    - "no_intra_emphasis"
    - "smart"
    - "strikethrough"
    - "superscript"
    - "tables"
    - "underline"
highlighter: "rouge"

gems:
  - "jekyll-archives"
  - "jekyll-feed"
  - "jekyll-paginate"
  - "jekyll-sitemap"
  - "jekyll-seo-tag"

jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layouts:
    year: "year-archive"
    month: "month-archive"
    category: "category-archive"
    tag: "tag-archive"
  permalinks:
    year: "/archive/:year/"
    month: "/archive/:year/:month/"
    category: "/category/:name/"
    tags: "/tag/:name/"
